### ISSUE TITLE
Error when  setting "metrics_enabled = true" to terraform code

### ISSUE THREAD

**Issue by SynitiSmug** [terraform-iaac/terraform-helm-nginx-controller#11]
When I attempt to enable metrics for my nginx ingress controller via terraform, Terraform errors out with the following:

`Error: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"`

Has anyone else faced this issue?

**Comment by bohdantverdyi** [comment]
Hello, it works only if you have `prometheus-operator`
