### ISSUE TITLE
i dont understand where you pointing on source field 

### ISSUE THREAD

**Issue by ghost** [terraform-iaac/terraform-helm-nginx-controller#14]
i want to deploy this module but i don'  get where are you poiting on the source line there is nothing called like that in this repo  "terraform-iaac/nginx-controller/helm"

resource "google_compute_address" "ingress_ip_address" {
  name = "nginx-controller"
}

module "nginx-controller" {
  source  = "terraform-iaac/nginx-controller/helm"

  ip_address = google_compute_address.ingress_ip_address.address
}

**Comment by bohdantverdyi** [comment]
Hello , this module is published to Terraform Registry

https://registry.terraform.io/modules/terraform-iaac/nginx-controller/helm/latest
