### ISSUE TITLE
additional_set only accepts string

### ISSUE THREAD

**Issue by mark-webster-catalyst** [terraform-iaac/terraform-helm-nginx-controller#16]
`additional_set` only accepts string values, but not everything is a string. For example `controller.service.loadBalancerSourceRanges` requires an array, but the module gives the error `Inappropriate value for attribute "value": string required.` if an array is given.

**Comment by bohdantverdyi** [comment]
Hi, could you give an example of your value ?

**Comment by mark-webster-catalyst** [comment]
Sure, `loadBalancerSourceRanges` takes a list of IP addresses to accept traffic from, for example:
```
[
  111.111.111.111/32,
  222.222.222.222/32,
  333.333.333.333/32
]
```
If I provide a string, to make the module happy, I get: `invalid type for io.k8s.api.core.v1.ServiceSpec.loadBalancerSourceRanges: got "string", expected "array"`

**Comment by bohdantverdyi** [comment]
i think you have to try this:
```hcl
{
  name = "controller.service.loadBalancerSourceRanges[0]"
  value = " 111.111.111.111/32"
},
{
  name = "controller.service.loadBalancerSourceRanges[1]"
  value = " 222.222.222/32"
},etc..
```

**Comment by bohdantverdyi** [comment]
Support for list will be in next releases in helm provider
https://github.com/hashicorp/terraform-provider-helm/pull/1071

**Comment by mark-webster-catalyst** [comment]
Nice, thank you for the info and response. Closing.

**Comment by mark-webster-catalyst** [comment]
Re-opening and creating pull request to support set_list

**Comment by bohdantverdyi** [comment]
@mark-webster-catalyst Thank you!
