### ISSUE TITLE
The argument "additional_set" is required, but no definition was found.

### ISSUE THREAD

**Issue by bartonjelles3** [terraform-iaac/terraform-helm-nginx-controller#18]
Looks like this was caused in commit a15dd3c by removing the default value for additional_set.

Workaround: Use an empty set (additional_set = []).

More than willing to open a PR!

**Comment by bohdantverdyi** [comment]
Hello, thanks for info, will fix this in a few hours

**Comment by bohdantverdyi** [comment]
Fixed, use v2.2.1 version please.
