### ISSUE TITLE
Support for 'atomic' helm releases

### ISSUE THREAD

**Issue by PJ-ISC** [terraform-iaac/terraform-helm-nginx-controller#2]
Would it be an option to have the 'atomic' parameter which can be used on the helm release itself, as input for this module as well?

**Comment by bohdantverdyi** [comment]
Hello, what do you mean atomic releases ?

**Comment by PJ-ISC** [comment]
Atomic as documented here: https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release#atomic

To prevent having a failed release/half release of the nginx controller.

**Comment by bohdantverdyi** [comment]
new tag is v2.0.1
