### ISSUE TITLE
chart name is "ingress-nginx"

### ISSUE THREAD

**Issue by ahmedatgithub** [terraform-iaac/terraform-helm-nginx-controller#20]
This is more of a question than an issue. I noticed that the chart "name" when I do a terraform plan is filled in as "ingress-nginx" which confused me.
I thought "ingress-nginx" is a separate projcet by the kubernetes team, whereas this is the "nginx-ingress" project.

What am I missing here? Can I change the chart name to minimize the confusion?
thx.

**Comment by ahmedatgithub** [comment]
See this Medium blog:
https://grigorkh.medium.com/there-are-two-nginx-ingress-controllers-for-k8s-what-44c7b548e678

**Comment by bohdantverdyi** [comment]
in artifact.io, chart has https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx name

**Comment by ahmedatgithub** [comment]
Thanx for calrifying, 

My bad, I was under the impression that the module was using the Nginix-Ingress controller chart from Nginx Inc., that's described here:
https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-helm/
because the title and other names are referring to "nginx-ingress" instead of "ingress-nginx"

It's a very confusing naming choice on both sides.
