### ISSUE TITLE
Associate Security group to AWS Load Balancer

### ISSUE THREAD

**Issue by vijayreddiar** [terraform-iaac/terraform-helm-nginx-controller#21]
[NLB now supports Security groups](https://aws.amazon.com/about-aws/whats-new/2023/08/network-load-balancer-supports-security-groups/) and can enable security groups on NLB by using [AWS Load Balancer controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller) version 2.6.0 or later. 

But unable to associate security group to nlb created through this module by adding below annotation.

```
   {
      name  = "controller.service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-security-groups"
      value = "<sg-name>"
      type  = "string"
    }
```

It's not throwing any error, but this section is completely ignored and we could see in the console that there is no security group associated to the newly created NLB.

<img width="677" alt="image" src="https://github.com/terraform-iaac/terraform-helm-nginx-controller/assets/61137483/fb702c38-2c89-4153-95d1-36949db1a0f4">

**Comment by vijayreddiar** [comment]
Is there any chance to get a solution for this?

**Comment by bohdantverdyi** [comment]
Hi, @vijayreddiar it could be potential problem with AWS.
Have you checked is this annotation exsits in ingress-controller service ?

**Comment by bohdantverdyi** [comment]
@vijayreddiar BTW, this module does't deploy AWS LoadBalancer controller, becuase this annotation which you provided only for this type of controller.

Module deploys this controller: https://kubernetes.github.io/ingress-nginx/

**Comment by vijayreddiar** [comment]
@bohdantverdyi PFB the `additional_set` used along with this module and everything works except security groups association to NLB.

```
   {
      name  = "controller.service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-backend-protocol"
      value = "ssl"
      type  = "string"
    },
    {
      name  = "controller.service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-ssl-cert"
      value = var.eks.certificate_arn
      type  = "string"
    },
    {
      name  = "controller.service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-ssl-ports"
      value = "443"
      type  = "string"
    },
    {
      name  = "controller.service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-ssl-negotiation-policy"
      value = "ELBSecurityPolicy-TLS13-1-2-2021-06"
      type  = "string"
    },
    {
      name  = "controller.service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-alpn-policy"
      value = "HTTP2Preferred"
      type  = "string"
    },
    {
      name  = "controller.service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-cross-zone-load-balancing-enabled"
      value = "true"
      type  = "string"
    },
    {
      name  = "controller.service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-scheme"
      value = "internal"
      type  = "string"
    },
    {
      name  = "controller.service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-manage-backend-security-group-rules"
      value = "false"
      type  = "string"
    },
    {
      name  = "controller.service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-name"
      value = "nlb-eks-ingress-controller"
      type  = "string"
    },
    {
      name  = "controller.service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-nlb-target-type"
      value = "ip"
      type  = "string"
    },
    {
      name  = "controller.service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-subnets"
      value = join("\\,", data.aws_eks_cluster.eks.vpc_config[0].subnet_ids)
      type  = "string"
    },
    {
      name  = "controller.service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-target-group-attributes"
      value = "preserve_client_ip.enabled=true"
      type  = "string"
    },
    {
      name  = "controller.service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-type"
      value = "external"
      type  = "string"
    },
    {
      name  = "controller.service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-private-ipv4-addresses"
      value = join("\\,", var.nlb_private_ips)
      type  = "string"
    },
    {
      name  = "controller.service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-security-groups"
      value = "sgp-nlb-eks-ingress-controller"
      type  = "string"
    }
```


All the required annotation to include in `additional_set` is collected from [here](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/guide/service/annotations/)

The annotation [aws-load-balancer-security-groups](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/guide/service/annotations/#security-groups) is available only from v2.6.0, so I suspect it could be something to do with wrong version reference when used within module.

When we create NLB using [lb resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb), we are able to associate Security Group. So, AWS works as expected and allow such association now.

**Comment by bohdantverdyi** [comment]
You check the docs which is for AWS Load Balancer ingress controller. This docs is not suitable for this ingress controller. 

You have to find annotation for k8s service with type loadbalancer. It's even not related to ingress, just k8s service with type LoadBalancer

**Comment by vijayreddiar** [comment]
Thanks, this issue stands resolved.

We had deployed `aws-load-balancer-controller` helm chart of version `1.5.3` which is now upgraded to [1.6.1](https://github.com/aws/eks-charts/blob/master/stable/aws-load-balancer-controller/Chart.yaml) that uses `aws-load-balancer-controller` [ v2.6.1](https://github.com/kubernetes-sigs/aws-load-balancer-controller/tree/v2.6.1)
