### ISSUE TITLE
duplicate allow-snippet-annotations in helm release

### ISSUE THREAD

**Issue by javedpawapay** [terraform-iaac/terraform-helm-nginx-controller#23]
When an additional set value for allow-snippet-annotations is set to true, it does not override the default value from the Helm chart, which is set to false. Instead, both values (true and false) are being set in the Helm release. This results in a YAMLException due to duplicate mapping keys in the Helm release resources.

```
{
  name  = "controller.config.allow-snippet-annotations"
  value = "true"
}

```

Failed to load release: Failed to get helm release resources: YAMLException: duplicated mapping key (34:3)
31 | namespace: ingress-nginx
32 | data:
33 | allow-snippet-annotations: "false"
34 | allow-snippet-annotations: "true"
         --------^
35 | enable-real-ip: "true"
36 | force-ssl-redirect: "true"

**Steps to Reproduce**

1. Use the terraform-iaac/nginx-controller/helm module.
2. Set an additional value for allow-snippet-annotations to true as shown above.
3. Apply the Helm release using Terraform.
4. Observe the duplicate key error in the Helm release resources.

**Expected Behavior**
The value allow-snippet-annotations set in additional_set should override the default value from the Helm chart, preventing duplicate keys and ensuring the Helm release is applied successfully.

**Comment by bohdanbinahai** [comment]
Hello, according to values from ingres-nginx controller the path for allowSnippetAnnotations is: 
**controller.allowSnippetAnnotations**

So, your block should looks like this:
`
{
  name  = "controller.allowSnippetAnnotations"
  value = "true"
}
`

**Comment by bohdantverdyi** [comment]
Hello, according to values from ingres-nginx controller the path for allowSnippetAnnotations is: 
**controller.allowSnippetAnnotations**

So, your block should looks like this:
```
{
  name  = "controller.allowSnippetAnnotations"
  value = "true"
}
```

**Comment by javedpawapay** [comment]
Thanks, Its resolved.
