### ISSUE TITLE
Its possible create a ALB ?

### ISSUE THREAD

**Issue by xdie** [terraform-iaac/terraform-helm-nginx-controller#8]
When i try with this configuration :

```
module "nginx-controller" {
  source  = "terraform-iaac/nginx-controller/helm"

  additional_set = [
    {
      name  = "controller.service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-type"
      value = "alb"
      type  = "string"
    },
    {
      name  = "controller.service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-cross-zone-load-balancing-enabled"
      value = "false"
      type  = "string"
    }
  ]
}
```

but I get  Classic Load balancer. Thanks advance

**Comment by bohdantverdyi** [comment]
Hello, you need to use the [ALB Ingress Controller](https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html) , in case if you want to have ALB instead of NLB. 

This module works with [NGINX Ingress Controller](https://kubernetes.github.io/ingress-nginx/) .
