### ISSUE TITLE
getting the source IP on EKS

### ISSUE THREAD

**Issue by japrescott** [terraform-iaac/terraform-helm-nginx-controller#9]
According to the [guide of nginx-ingress](https://kubernetes.github.io/ingress-nginx/user-guide/miscellaneous/#source-ip-address) one needs to set `use-proxy-protocol: "true"` which I do the following way;

```
...
additional_set = [
        {
          name  = "controller.service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-type"
          value = "alb"
          type  = "string"
        },
        {
          name  = "controller.service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-cross-zone-load-balancing-enabled"
          value = "true"
          type  = "string"
        },
        {
          name  = "controller.config.enable-real-ip"
          value = "true"
        },
        {
          name  = "controller.config.compute-full-forward-for"
          value = "true"
        },
        {
          name  = "controller.config.use-forwarded-headers"
          value = "true"
        },
]
...
```

However I am not getting this to work. The `x-forwarded-for` and `x-real-ip` is always the IP of the nginx-ingress-controller pod. 

According to the docs, `proxy-real-ip-cidr` should be set as well. However, how do I obtain the cidr if the LB as thats configured by this chart itself? Feels like a chicken and egg problem I can't wrap my head around and would appreciate some guidance.

/Edit: also manually setting `proxy-real-ip-cidr` to the VPC IPV4 CIDR does not give me the expected results.

Thank you

**Comment by japrescott** [comment]
for anyone stumbling on this, I was able to make it happen although I am unsure if thats best practice;

```
        {
          name  = "controller.service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-type"
          value = "alb"
          type  = "string"
        },
        {
          name  = "controller.service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-proxy-protocol"
          value = "*" # enable proxy protocol needed for getting the real IP
          type  = "string"
        },
        {
          name  = "controller.service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-cross-zone-load-balancing-enabled"
          value = "true"
          type  = "string"
        },
        {
          name  = "controller.config.use-proxy-protocol"
          value = "true"
        },
```

**Comment by bohdantverdyi** [comment]
Hello, this controller good to use with NLB, not ALB. From the box NLB works good with client ips.

If you would like to use ALB, i think better option is [AWS Load Balancer controller](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v1.1/)

**Comment by bohdantverdyi** [comment]
@japrescott

**Comment by japrescott** [comment]
@bohdantverdyi thank you for your reply and suggestion. Would you perhaps have a full example?

**Comment by bohdantverdyi** [comment]
I haven't tried AWS LB Controller yet. Sorry can't help you) @japrescott
